### ISSUE TITLE
Identify variables that need to be modified 

### ISSUE THREAD

**Issue by twitte01** [twitte01/232R_GroupProject#42]
- What variables need to be removed? 
- What categories need to be combines?

**Comment by CanIGetAnAman** [comment]
Could look into an "income per age group." Maybe group by 20s, 30s, etc

**Comment by twitte01** [comment]
I am hoping that clustering does help naturally split age groups with other variables 

> Could look into an "income per age group." Maybe group by 20s, 30s, etc
