### ISSUE TITLE
Variables Removal & Modification - Household

### ISSUE THREAD

**Issue by twitte01** [twitte01/232R_GroupProject#60]

**Comment by PraveenManimaran** [comment]
Remove variables with lots of null values
Variables to be removed with large null count and N/A : 'MET2023', 'COUPLETYPE', 'CINETHH', 'TAXINCL', 'INSINCL' 
Variables not relevant: 'SAMPLE', 'SERIAL', 'CBSERIAL', 'HHWT', 'CLUSTER', 'CPI99', 'STRATA',

Things to consider: 'ARENTGRS', 'AMOBLHOME' have lots of 0's which indicate that they are considered N/A so should consider removing in future.
