### ISSUE TITLE
Determine Feature Expansion Needed

### ISSUE THREAD

**Issue by twitte01** [twitte01/232R_GroupProject#9]

**Comment by CanIGetAnAman** [comment]
We could combine all of the utility costs into 1 feature "utilities"

**Comment by twitte01** [comment]
Combine education attainment with if current in school

**Comment by twitte01** [comment]
citizenship status with race may be interesting

**Comment by twitte01** [comment]
potentially combine work variables (detailed class of work, looking for work) could potentially include if looking for work, hours worked and income

**Comment by CanIGetAnAman** [comment]
combine individual utility costs into 1 column "COSTUTIL", and created a column called "FULLTIME" that is a 1 if they work 40+ hours a week, and a 0 otherwise
